using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ScopeGenerator
{
    [Generator]
    public class ScopeAttributeGenerator: ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            
        }

        public void Execute(GeneratorExecutionContext context)
        {
            string code = $@"// <auto-generated />
using System;

namespace Sample;

public static class MyGeneratedClass 
{{
    public static string HelloWorld() 
    {{
        return ""hello world"";
    }}

}}
";
            
            
            context.AddSource("GeneratedCode.g.cs", SourceText.From(code));
        }
    }
}